before_script:
    - angr-test sync

simuvex:
    script: "angr-test simuvex"
    tags:
        - "angr"
    except:
        - "master"

angr:
    script: "angr-test angr"
    tags:
        - "angr"
    except:
        - "master"

fidget:
    script: "angr-test fidget"
    tags:
        - "angr"
    except:
        - "master"

simuvex_lint:
    script: "angr-test lint"
    tags:
        - "angr"
    except:
        - "master"
