before_script:
    - which angr-test && angr-test sync hard

identifier:
    script: "angr-test identifier"
    tags:
        - "angr"

patcherex:
    script: "angr-test patcherex"
    tags:
        - "angr"
