language: python
python: 2.7
sudo: required
dist: xenial
env:
  - PY=e ANGR_REPO=angr
  - PY=e ANGR_REPO=angr-doc
  - PY=e ANGR_REPO=angrop
  - PY=e ANGR_REPO=fuzzer
  - PY=e ANGR_REPO=driller
  - PY=p ANGR_REPO=colorguard
  - PY=e ANGR_REPO=fidget
#  - PY=e ANGR_REPO=tracer NOSE_OPTIONS="-x" NOSE_PROCESSES=1
#  - PY=p ANGR_REPO=rex NOSE_OPTIONS="-x" NOSE_PROCESSES=1
#  - PY=e ANGR_REPO=patcherex NOSE_OPTIONS="-x" NOSE_PROCESSES=1
install: (sudo apt-get update || true) && cd && git clone https://github.com/angr/angr-dev && cd angr-dev && bash -e ./setup.sh -i -w -v -$PY angr tracer fuzzer driller povsim compilerex rex colorguard fidget identifier patcherex
script: cd ~/angr-dev && source ~/.virtualenvs/angr/bin/activate && ./travis-test.sh
